name: Nightly bulids

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if bubblewrap had a commit in the last day
        run: |
          bash -c "${{ github.workspace}}/should_rebuild.sh"
      - name: Build
        run: |
            bash -c "${{ github.workspace }}/build.sh"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bubblewrap-static-*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: bubblewrap-static-*.tar.xz
          commit: main
          name: ${{ env.BWRAP_VER }}
