name: Nightly builds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/12 * * *"
  push:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if bubblewrap had a commit in the last day
        run: |
          bash -c "${{ github.workspace }}/should_rebuild.sh"
        if: github.event_name == 'schedule'
      - name: Build
        run: |
          sudo -E bash -c "${{ github.workspace }}/build.sh"
      - name: Create a tag
        run: |
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/git/tags \
              -d '{"tag":"${{ env.BWRAP_VER }}","message":"automated commit","object":"${{ github.sha }}","type":"commit"}'
        if: github.ref_name == 'main'
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bwrap
          commit: main
          name: ${{ env.BWRAP_VER }}
          tag: ${{ env.BWRAP_VER }}
        if: github.ref_name == 'main'
