name: Nightly bulids

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if bubblewrap had a commit in the last day
        run: |
          bash -c "${{ github.workspace}}/should_rebuild.sh"
      - name: Build
        run: |
            bash -c "${{ github.workspace }}/build.sh"
      - name: Create a tag
        run: |
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.repository.name }}/git/tags \
            -d '{"tag":${{ env.BWRAP_VER }},"message":"automated commit","object":"${GITHUB_SHA}","type":"commit"}'
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bubblewrap-static-*.tar.xz
          commit: main
          name: ${{ env.BWRAP_VER }}
          tag: ${{ env.BWRAP_VER }}
